version: "3"

services:
    pharos-control:
        container_name: pharos-control
        image: ghcr.io/jmacalinao/pharos-control-docker
        restart: always
        ports:
            - 9321:9321
        volumes:
            - pharos-config:/app/config

volumes:
    pharos-config:
